#!/bin/bash

cd ~
git init --initial-branch master
git remote add origin git@github.com:dundargoc/dotfiles.git
git fetch
git checkout -f master

# To get gh-default-branch to work
git remote set-head origin -a

# Tmux plugin manager
git clone --depth=1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# NOTE: on Windows the user profile seems to always be located at $profile.
