#!/bin/bash

while (($# > 0)); do
  case $1 in
  --all) # format all files
    ALL=1
    shift
    ;;
  esac
done

repo_path="$HOME/programs/neovim"
source_path="$HOME/programs/neovim/src/nvim"
config_path="$HOME/programs/neovim/src/uncrustify.cfg"
grep_pattern='\.[ch]$'
format_files=($(find "$source_path" -name '*.[h,c]'))

default_branch=$(git -C "$repo_path" rev-parse --abbrev-ref origin/HEAD | sed 's|origin/||')
current_branch=$(git -C "$repo_path" branch --show-current)

if [[ $default_branch != "$current_branch" ]] && [[ -z $ALL ]]; then
    ancestor_commit=$(git -C "$repo_path" merge-base "$default_branch" "$current_branch")
    files=$(git -C "$repo_path" diff --name-only --line-prefix="$repo_path"/ "$ancestor_commit"..."$current_branch")
    files2=$(git -C "$repo_path" diff --name-only --line-prefix="$repo_path"/)
    files3=$(git -C "$repo_path" diff --cached --name-only --line-prefix="$repo_path"/)
    format_files=( $files $files2 $files3 )
    format_files=($(echo "${format_files[@]}" | tr ' ' '\n'  | grep -E "$grep_pattern" | sort -u | tr '\n' ' '))
fi

for i in "${format_files[@]}"; do
        uncrustify -c "$config_path" --replace --no-backup "$i" &
done
wait
