#!/usr/bin/env python3

import subprocess
import platform


def ubuntu():
    subprocess.call(["aptitude", "search", "~i!~M"])


def manjaro():
    package_info_raw = subprocess.check_output(["paclog"], text=True).strip()
    package_info_raw_split = package_info_raw.split("\n")

    package_latest_action = {}

    for package_line in package_info_raw_split:
        package_split = package_line.split()

        action = package_split[2]
        package = package_split[3]
        if action in ["installed", "removed"]:
            if package in package_latest_action:
                package_latest_action.pop(package)
            package_latest_action[package] = action

    explicitly_installed_packages_line = subprocess.check_output(
        ["pacman", "-Qe"], text=True
    ).strip()

    explicitly_installed_packages = {
        i.split()[0] for i in explicitly_installed_packages_line.split("\n")
    }

    for k, v in package_latest_action.items():
        if v == "installed" and k in explicitly_installed_packages:
            print(k)


if __name__ == "__main__":
    if "ubuntu" in platform.version().lower():
        ubuntu()
    else:
        manjaro()

# vim: noet:
