#!/usr/bin/env python3

import subprocess
import os
import sys
import secrets
from pathlib import Path
import argparse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--type", default="chore")
    args = parser.parse_args()

    return args


def main():
    repo_path = subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], text=True
    ).strip()
    HOME = os.environ["HOME"]

    if repo_path not in [
        f"{HOME}/programs/dundar-organization/neovim",
        f"{HOME}/programs/notdundargoc/neovim",
    ]:
        sys.exit("Attempting dangerous command outsite of intended area. Abort")

    branch = f"ci-test/{secrets.token_hex(5)}"

    args = parse_args()

    subprocess.call(["git", "checkout", "--quiet", "-b", branch])

    filename = Path(repo_path) / ".test"
    filename.write_text("")

    subprocess.call(["git", "add", "-A"])
    subprocess.call(["git", "commit", "--quiet", "-m", f"{args.type}: CI test"])
    subprocess.call(
        ["git", "push", "--quiet", "--set-upstream", "origin", branch],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    subprocess.call(["gh", "pr", "create", "--fill", "-R", "neodundar/neovim"])
    subprocess.call(["git", "switch", "--quiet", "master"])


if __name__ == "__main__":
    main()
