#!/usr/bin/env python

import subprocess
import os
import sys
from pathlib import Path


def disable_all_workflows():
    active_workflows = subprocess.check_output(
        ["gh", "workflow", "list"], text=True
    ).splitlines()
    for workflow in active_workflows:
        workflow_name = workflow.split("\t")[0]
        subprocess.call(["gh", "workflow", "disable", workflow_name])


def cancel_all_runs():
    runs = subprocess.check_output(["gh", "run", "list"], text=True).splitlines()
    for run in runs:
        splitrun = run.split("\t")
        run_status = splitrun[0]
        id = splitrun[6]
        if run_status in ["queued", "in_progress"]:
            subprocess.call(["gh", "run", "cancel", id])


def login(user):
    hosts_path = Path(os.environ["XDG_CONFIG_HOME"]) / "gh" / "hosts.yml"
    hosts_path.unlink(missing_ok=True)

    token_path = (
        Path(os.environ["HOME"]) / ".private-dotfiles" / "token" / f"{user}-gh-cli"
    )

    with open(token_path) as f:
        subprocess.run(["gh", "auth", "login", "--with-token"], text=True, stdin=f)


def main():
    repo_path = subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], text=True
    ).strip()
    HOME = os.environ["HOME"]

    if repo_path not in [f"{HOME}/programs/dundar-organization/neovim"]:
        sys.exit("Attempting VERY dangerous command outsite of intended area. Abort")

    login("dundargoc")
    disable_all_workflows()
    cancel_all_runs()

    login("notdundargoc")
    all_branches = [
        i.strip()
        for i in subprocess.check_output(["git", "branch"], text=True).splitlines()
    ]
    remote_branches = [
        i.strip()
        for i in subprocess.check_output(
            ["git", "branch", "--remote"], text=True
        ).splitlines()
    ]
    api_branch = "origin/marvim/api-doc-update/master"

    test_branches = [i for i in all_branches if i.startswith("ci-test/")]
    if api_branch in remote_branches:
        test_branches.append(api_branch.replace("origin/", ""))

    for branch in test_branches:
        subprocess.call(["git", "push", "origin", "--delete", branch])
        subprocess.call(["git", "branch", "--delete", "--force", branch])

    login("dundargoc")


if __name__ == "__main__":
    main()
