#!/usr/bin/env python3

import subprocess
import os
import sys


def disable_all_workflows():
    active_workflows = subprocess.check_output(
        ["gh", "workflow", "list"], text=True
    ).splitlines()
    for workflow in active_workflows:
        workflow_name = workflow.split("\t")[0]
        subprocess.call(["gh", "workflow", "disable", workflow_name])


def cancel_all_runs():
    runs = subprocess.check_output(["gh", "run", "list"], text=True).splitlines()
    for run in runs:
        splitrun = run.split("\t")
        run_status = splitrun[0]
        id = splitrun[6]
        if run_status in ["queued", "in_progress"]:
            subprocess.call(["gh", "run", "cancel", id])


def main():
    repo_path = subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], text=True
    ).strip()
    HOME = os.environ["HOME"]

    if repo_path not in [f"{HOME}/programs/dundar-organization/neovim"]:
        sys.exit("Attempting VERY dangerous command outsite of intended area. Abort")

    disable_all_workflows()
    cancel_all_runs()

    all_branches = [
        i.strip()
        for i in subprocess.check_output(["git", "branch"], text=True).splitlines()
    ]
    test_branches = [i for i in all_branches if i.startswith("ci-test/")]
    for branch in test_branches:
        subprocess.call(["git", "push", "origin", "--delete", branch])
        subprocess.call(["git", "branch", "--delete", "--force", branch])


if __name__ == "__main__":
    main()
