[files]
extend-exclude = ["*.po", "bigfile_oneline.txt"]

[default]
extend-ignore-words-re = ['\b\w{1,4}\b']

[default.extend-words]
alloced = "alloced"
charcol = "charcol"
inout = "inout"
iterm = "iterm"
tolen = "tolen"
windo = "windo"
