[files]
extend-exclude = ["*.po", "bigfile_oneline.txt"]

[default.extend-words]
alloced = "alloced"
ba = "ba"
charcol = "charcol"
clen = "clen"
dout = "dout"
enew = "enew"
fo = "fo"
inex = "inex"
inout = "inout"
iterm = "iterm"
mak = "mak"
nd = "nd"
parm = "parm"
sav = "sav"
teh = "teh"
tolen = "tolen"
tpos = "tpos"
ue = "ue"
windo = "windo"
