[files]
extend-exclude = ["*.po"]

[default.extend-words]
alloced = "alloced"
ba = "ba"
charcol = "charcol"
dout = "dout"
enew = "enew"
fo = "fo"
inex = "inex"
iterm = "iterm"
mak = "mak"
nd = "nd"
parm = "parm"
sav = "sav"
teh = "teh"
tolen = "tolen"
ue = "ue"
windo = "windo"
